  name: first workflow
  on:
    push:
      branches:
        - main
    fork:
  jobs:
    job1:
      environment: Dev 
      runs-on: ubuntu-latest
      steps:
        - run: echo "hello world from env ${{ vars.name }}"
        - name: checkout
          uses: actions/checkout@v6.0.2
        - run: tree

        - name: idk
          run: git status
    prod:
      environment: Prod
      runs-on: ubuntu-latest
      steps:
        - run: echo "Prod"
    
    job-ts-test:
      environment: Dev
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v6.0.2
        - uses: ./.github/actions/action-ts-1
